maki_new/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from maki_new import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls', namespace='shop')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.GoodsList.as_view(), name='index'),
    path('reg_user', views.UserRegistration.as_view(), name='user_registration'),
    path('<int:pk>', views.GoodDetail.as_view(), name='detail'),
    path('comment', views.CommentSave.as_view(), name='comment_save'),
    path('add_to_basket/<int:pk>', views.add_to_basket, name='add_to_basket'),
    path('remove_from_basket', views.del_good_from_basket, name='remove_good'),
    path('basket', views.BasketShow.as_view(), name='basket'),
    path('order', views.Order.as_view(), name='order'),
    path('oder_id/<int:pk>', views.show_order, name="show_order"),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm


class Good(models.Model):
    name = models.CharField(max_length=120, null=False, blank=False, help_text='назва товару')
    price = models.FloatField(blank=False, null=False, default=0, help_text='ціна товару')
    quantity = models.IntegerField(default=0, help_text="кількість доступних одиниць")
    descriprion = models.CharField(max_length=500, help_text='описання товару')
    category = models.CharField(max_length=1, choices=(('b', 'bouket'), ('g', 'gift'), ('k', 'komposition')),
                                default='b')
    goot_item = models.CharField(max_length=11,
                                 choices=(('item_hit', 'item_hit'),
                                          ('item_action', 'item_action'),
                                          ('item_new', 'item_new'),
                                          ('', '')),
                                 default='', blank=True)
    img_content = models.ImageField(upload_to='content/', help_text='картинка для переліку', default='')
    img1 = models.ImageField(upload_to='img/', help_text='перша картинка для відображення')
    img2 = models.ImageField(upload_to='img/',
                             help_text='ще одна картинка для відображення', blank=True, null=True)
    img3 = models.ImageField(upload_to='img/',
                             help_text='картинка для відображення', blank=True, null=True)

    @property
    def availability(self):
        return bool(self.quantity > 0)


class Comments(models.Model):
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    rating = models.IntegerField(choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)), default=5)
    date = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-date']


class CommemtForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['good', 'user', 'text']


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date_order = models.DateField(auto_now=True)
    sended = models.BooleanField(default=False)
    paied = models.BooleanField(default=False)

    send = models.BooleanField(default=False)
    date_resive = models.DateTimeField(auto_now=True)
    address_city = models.CharField(max_length=300, blank=True, default="")
    address_local = models.CharField(max_length=300, default='')
    receiver_name = models.CharField(max_length=100, blank=True, null=True)
    receiver_sename = models.CharField(max_length=100, blank=True, null=True)
    receiver_lastname = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=12, blank=True, null=True)
    receiver_card = models.BooleanField(default=False)
    receiver_text = models.CharField(max_length=1000, blank=True, default="")
    sum_total = models.FloatField(default=0)

    def __str__(self):
        return self.user.username + " " + str(self.date_order)


class FormOrder(ModelForm):
    class Meta:
        model = Order
        # fields = ['address_city', 'ad' 'phone', 'sum_total', 'send']
        exclude = ['date_order', 'sended', 'paied']
        # widgets = {
        #     'date_resive': DateInput(attrs={'type': 'date'})
        # }


class GoodsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.good.id) + " " + self.good.name

shop/views.py
import json
from pprint import pprint

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.forms import formset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.views import generic
from .models import *
from django import forms


class TopGoodsCookiesMixin:
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['top_goods'] = Good.objects.all()[:5]
        quantity = 0
        summa = 0
        for item in self.request.session.keys():
            if 'good_' in item:
                q = int(self.request.session.get(item))
                try:
                    quantity += q
                    summa += q * Good.objects.get(pk=int(item[5:])).price
                except:
                    pass
        context['total_quantity'] = quantity
        context['sum'] = summa
        context['user_id'] = self.request.user.id
        try:
            context['top_comments'] = Good.objects.get(pk=self.kwargs['pk']).comments_set.all()[:3]
        except:
            pass
        context['order'] = False
        context['sum_and_send'] = summa + 500
        return context


class GoodsList(TopGoodsCookiesMixin, generic.ListView):
    model = Good
    paginate_by = 2


class GoodDetail(TopGoodsCookiesMixin, generic.DetailView):
    model = Good

    # http_method_names = ['get', 'post']

    def get_context_data(self, *, object_list=None, **kwargs):
        if self.request.GET.get('q'):
            self.request.session['good_' + str(self.kwargs['pk'])] = int(self.request.GET.get('q'))
        context = super().get_context_data(object_list=None, **kwargs)
        context['quantity'] = self.request.session.get('good_' + str(self.kwargs['pk']), 1)

        return context


def add_to_basket(request, pk):
    good = 'good_' + str(pk)
    quantity = request.session.get(good, 0) + int(request.GET.get('q'))
    request.session[good] = quantity
    return redirect('shop:index')


def del_good_from_basket(request):
    request.session.pop(request.GET.get('remove'))
    return redirect('shop:basket')


class CommentSave(LoginRequiredMixin, generic.CreateView):
    model = Comments
    form_class = CommemtForm

    def get_form_kwargs(self):
        kwards = super(CommentSave, self).get_form_kwargs()
        self.success_url = kwards['data']['url']
        return kwards

    def form_invalid(self, form):
        messages.success(self.request, "Треба щось писати")
        return redirect(self.success_url)


class BasketShow(TopGoodsCookiesMixin, generic.TemplateView):
    template_name = "shop/good_basket.html"

    def get_context_data(self, **kwargs):
        context = super(BasketShow, self).get_context_data(**kwargs)
        goods = []
        total_sum = 0
        for good_key in self.request.session.keys():
            if 'good_' not in good_key: continue
            good = Good.objects.get(pk=int(good_key[5:]))
            summ = good.price * int(self.request.session[good_key])
            total_sum += summ
            goods.append((good, int(self.request.session[good_key]), summ))
        context['goods'] = goods
        context['total_summ'] = total_sum
        context['order'] = True
        return context


class Order(TopGoodsCookiesMixin, LoginRequiredMixin, generic.CreateView):
    template_name = 'shop/good_order.html'
    model = Order
    form_class = FormOrder
    success_url = "shop:index"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = True
        return context

    def form_valid(self, form):
        pprint(form.cleaned_data)
        order = form.save()

        # save goods into DB
        good_key_list = list(self.request.session.keys())
        for good_key in good_key_list:
            if 'good_' not in good_key: continue
            good = Good.objects.get(pk=int(good_key[5:]))
            quantity = int(self.request.session.get(good_key))
            try:
                GoodsInOrder.objects.create(order=order, good=good, quantity=quantity)
                del self.request.session[good_key]
            except:
                pass
        return super().form_valid(form)


class FormUserRegistration(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        exclude = ['groups', 'user_permissions', 'is_staff', 'is_superuser',
                   'is_active', 'date_joined', 'last_login', 'last_name']


class UserRegistration(TopGoodsCookiesMixin, generic.CreateView):
    form_class = FormUserRegistration
    # model = User
    template_name = "shop/user_registration.html"
    success_url = '/'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        print(user)
        User.objects.create(user=user)


def show_order(request, pk):
    properties_from_order = list(('name', 'price', 'quantity',))
    goods_in_order = GoodsInOrder.objects.filter(order_id=pk). \
        values_list('good__name', 'good__price', 'quantity')
    rez = [dict(zip(properties_from_order, i)) for i in list(goods_in_order)]
    return JsonResponse(rez, safe=False)

templates/shop/good_basket.html
{% extends 'generic_template.html' %}
{% load staticfiles %}
{% block content %}
    <div class="orderpage">
        <div class="wrapper">
            <div class="pr__order-container">
                <div class="pr-order">
                    <p class="unit__title"><span class="unit__num">1</span>Ваш заказ</p>
                    <div class="pr-order__box">
                        <div class="pr-order__table">
                            <div class="pr-order__head">
                                <p class="pr-order__element element__name">Наименование</p>
                                <p class="pr-order__element"></p>
                                <p class="pr-order__element element__price">Цена &#8381;</p>
                                <p class="pr-order__element element__amount">Количество</p>
                                <p class="pr-order__element element__sum">Сумма &#8381;</p>
                            </div>
                            {% for good, quontity, summ in goods %}
                                <div class="pr-order__item">
                                    <div class="item_photo"><a href="{% url 'shop:detail' good.id %}"><img
                                            src="{{ good.img_content.url }}" alt=""></a></div>
                                    <div class="item__name"><a
                                            href="{% url 'shop:detail' good.id %}">{{ good.name }}</a></div>
                                    <div class="item__price">{{ good.price }} руб.</div>
                                    <div class="item__count">
                                        <div class="order__quantity-container"><a href="#"
                                                                                  class="order__quantity-button order__minus">-</a>
                                            <input type="text" value="{{ quontity }}" name="order__count"
                                                   maxlength="4" class="order__count"><a href="#"
                                                                                         class="order__quantity-button order__plus">+</a>
                                        </div>
                                    </div>
                                    <div class="item__sum">{{ summ }} руб.</div>
                                    <div class="item__price">
                                        <a href="{% url 'shop:remove_good' %}?remove=good_{{ good.id }}">Видалити</a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="pr-order__sum">
                            <p>Сумма:<span>{{ total_summ }} руб.</span></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="order__button" style="display: inline-block" href="{% url 'shop:order' %}">Заказать</a>
        </div>
    </div>
{% endblock %}

templates/shop/good_detail.html
{% extends 'generic_template.html' %}
{% load staticfiles %}

{% block content %}
    <div class="about">
        <div class="wrapper clearfix">
            <div class="col_pull">
                <div class="col_x2">
                    <div class="about__gallery">
                        <div class="gallery__img">

                        </div>
                        <div class="img__sm_wrap">
                            <div class="gallery__img_sm">
                                <a href="{{ good.img1.url }}" data-marker="1" data-alt="">
                                    <img src="{{ good.img1.url }}" alt="bouquets details">
                                </a>
                            </div>
                            <div class="gallery__img_sm">
                                <a href="{{ good.img2.url }}" data-marker="2" data-alt="">
                                    <img src="{{ good.img2.url }}" alt="bouquets details">
                                </a>
                            </div>
                            {% if good.img3 %}
                                <div class="gallery__img_sm">
                                    <a href="{{ good.img3.url }}" data-marker="3" data-alt="">
                                        <img src="{{ good.img3.url }}" alt="bouquets details">
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>


                    <div class="comments_md">
                        <div class="comments__top clearfix">
                            <span class="comments__title">Отзывы покупателей</span>
                            <span class="comments__quantity">{{ good.comments_set.all.count }} отзыва</span>
                        </div>
                        {% for comment in top_comments %}
                            <div class="comments__item">
                                <div class="comment__header clearfix">
                                    <div class="stars_recall rating_1x rating_2x rating_3x rating_4x rating_5x"></div>
                                    <p class="comment__date">{{ comment.date }}</p>
                                    <p class="comment__name">{{ comment.user.username }}</p>
                                </div>
                                <div class="comment__text">{{ comment.text }}</div>
                            </div>
                        {% endfor %}
                        <div class="comments__footer">
                            {% if good.comments_set.all.count  > 5 %}
                                <a href="#" class="comments__show-more">Показать еще</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="recall recall_md">
                        {% if user.is_authenticated %}
                            <div class="recall__header clearfix">
                                <div class="stars_recall rating_1x rating_2x rating_3x rating_4x rating_5x"></div>
                                <label for="recall" class="recall__title">Написать отзыв</label>
                            </div>
                            <form action="{% url 'shop:comment_save' %}" method="post">
                                {% if messages %}
                                    {% for message in messages %}
                                        <p> {{ message }}</p>
                                    {% endfor %}

                                {% endif %}

                                {% csrf_token %}
                                <input name="good" type="hidden" value="{{ good.id }}">
                                <input name="user" type="hidden" value="{{ user.id }}">
                                <input name="url" , type="hidden" value="{% url 'shop:detail' good.id %}">
                                <textarea name="text" id="recall" cols="30" rows="4"></textarea>
                                <button type="submit" class="btn_form">Отправить</button>
                            </form>
                        {% endif %}
                    </div>


                </div>
                <div class="col_x2">
                    <div class="order">
                        <p class="order__title">{{ good.name }}</p>
                        <div class="order__container">
                            <div class="order__main clearfix">
                                <form method="get" action="{% url 'shop:detail' good.id %}">
                                    {% csrf_token %}
                                    <div class="order__price-container">
                                        <p class="order__price">{{ good.price }} руб.</p>
                                        <div class="order__quantity">
                                            <p class="order__quantity-text">Количество</p>
                                            <div class="order__quantity-container"><a href="#"
                                                                                      class="order__quantity-button order__minus">-</a>
                                                <input type="text" value="{{ quantity }}" name="q" maxlength="4"
                                                       class="order__count"><a href="#"
                                                                               class="order__quantity-button order__plus">+</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="order__button-container">
                                        <input class="order__button" type="submit" value=" ЗАКАЗАТЬ" >
                                    </div>
                                </form>
                            </div>
                            <div class="order__footer">При заказе букета вы получите 3% бонусов или 90 рублей. Вы их
                                можете использовать при следующем заказе.
                            </div>
                        </div>
                    </div>
                    <div class="delivery">
                        <p class="delivery__title">Доставка</p>
                        <p class="delivery__item delivery__standart">С 9.00 до 24.00 - <span>500 руб.</span></p>
                        <p class="delivery__item delivery__nighttime">Доставка в ночное время - <span>700 руб.</span>
                        </p>
                    </div>
                    <div class="description">
                        <p class="description__title">Описание буклета</p>
                        <p class="description__text">{{ good.descriprion }}</p>
                    </div>

                </div>
            </div>
            <div class="clearfix"></div>

            <div class="partners__carousel">
                <div class="section__title carousel__title">Наши клиенты</div>
                <ul class="clearfix" id="partners">
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo1.png' %}" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo2.png' %}" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo3.png' %}" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo4.png' %}" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo5.png' %}" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/partners_logo6.jpg' %}" alt="">
                        </a>
                    </li>
                </ul>
            </div>


            <div class="product__carousel">
                <div class="section__title carousel__title">Вас может заинтересовать</div>
                <ul class="clearfix" id="gallery">
                    {% for good in top_goods %}
                        <li>
                            <div class="goods__item {{ good.good_item }}">
                                <a href="{% url 'shop:detail' good.id %}">
                                    <div class="goods__img">
                                        <img src="{{ good.img_content.url }}" alt="gift">
                                    </div>
                                </a>
                                <a class="goods__name" href="{% url 'shop:detail' good.id %}">{{ good.name }}</a>
                                <p class="goods__price">{{ good.price }} руб.</p>
                                <a href="#" class="goods__btn">Заказать</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>


        </div>
    </div>

{% endblock %}

templates/shop/good_order.html
{% extends 'generic_template.html' %}
{% load staticfiles %}

{% block content %}
    <div class="orderpage">
        <div class="wrapper">
            <form action="{% url 'shop:order' %}" method="post">
                {% csrf_token %}
                <div class="pr__order-container">
                    <div class="pr-order">
                        <p class="unit__title"><span class="unit__num">1</span>
                            Ваш заказ: {{ total_quantity }} товаров Сумма: <span>{{ sum }} руб.</span></p>
                    </div>
                </div>
                <input type="hidden" name="{{ form.user.name }}" value="{{ user_id }}">

                <div class="pr__delivery">
                    <div class="unit__title"><span class="unit__num">2</span>Доставка</div>
                    <div class="checkbox-row recipient_wrap send_method">
                        <div class="checkbox__container del-check">
                            <input type="radio" name="{{ form.send.name }}" value="sendClient" id="sendClient">
                            <label for="sendClient">Я получу заказ</label>
                        </div>
                        <div class="checkbox__container del-check">
                            <input type="radio" name="{{ form.send.name }}" value="sendRecipient" id="sendRecipient"
                                   checked>
                            <label for="sendRecipient">Отправить заказ адресату</label>
                        </div>
                    </div>
                    <div class="pr__delivery-form send_recipient">
                        <div class="delivery__form_wrap">
                            <div class="inputs-row">
                                <div class="inputs-row__title">Получатель:</div>
                                <div class="inputs_wrap">
                                    <input type="text" placeholder="Фамилия" name="{{ form.receiver_lastname.name }}">
                                    <input type="text" placeholder="Имя" name="{{ form.receiver_name.name }}">
                                    <input type="text" placeholder="Отчество" name="{{ form.receiver_sename.name }}">
                                    <input type="text" placeholder="Телефон" name="{{ form.phone.name }}">
                                </div>
                            </div>
                            <div class="inputs-row adress-row">
                                <div class="inputs-row__title">Адрес доставки:</div>
                                <div class="adress_cont">
                                    <div class="input-cont_wrap">
                                        <input type="text" placeholder="Город" name="{{ form.address_city.name }}"
                                               class="option_field">
                                        {#                                        <a href="" class="location_link"></a>#}
                                    </div>
                                    <input type="text" placeholder="ул. Советская, д. 62, кв. 3"
                                           name="{{ form.address_local.name }}">
                                </div>
                            </div>
                            <div class="inputs-row">
                                <div class="checkbox__container card__container">
                                    <input type="checkbox" name="{{ form.receiver_card.name }}" id="card">
                                    <label for="card">Добавить открытку бесплатно</label>
                                </div>
                            </div>
                            <div class="inputs-row delivery__text">
                                <textarea name="{{ form.receiver_text.name }}" cols="20" rows="10"
                                          placeholder="Текст"></textarea>
                            </div>
                            <div class="inputs-row delivery__time-date">
                                <div class="inputs-row__title">Дата и время доставки:</div>
                                <div class="data-time_cont">
                                    <div class="input-cont_wrap">
                                        <input type="text" placeholder="08.03.16" name="{{ form.date_resive.name }}"
                                               class="option_field">
                                        {#                                        <a href="#" class="pr__delivery__date"></a>#}
                                    </div>
                                    <div class="input-cont_wrap time-input">
                                        <input type="text" placeholder="00.00" name="time" class="option_field">
                                        {#                                        <a href="#" class="pr__delivery__time"></a>#}
                                    </div>
                                    <div class="delivery__work-time">
                                        <span class="text__divide">* С 9.00 до 24.00 - 500 руб.</span>
                                        <span class="text__divide">Доставка в ночное время - 700 руб.</span>
                                    </div>
                                </div>
                            </div>
                            <div class="delivery__price">
                                <div class="price__delivery">
                                    <p class="price__name">Стоимость доставки составит:</p>
                                    <p class="price__sum">500 руб.</p>
                                </div>
                                <div class="pice__sum">
                                    <p class="price__name price__name_red">Итого:</p>
                                    <p class="price__sum price__sum_red">{{ sum_and_send }} руб.</p>
                                    <input type="hidden" name="{{ form.sum_total.name }}" value="{{ sum_and_send }}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <input class="order__button" type="submit" value="Заказать">
            </form>


        </div>
    </div>
{% endblock %}

templates/shop/good_payment.html
{% extends 'generic_template.html' %}
{% load staticfiles %}

{% block content %}
    <div class="payment__section">
        <div class="payment__method">
            <div class="unit__title"><span class="unit__num">3</span>Оплата</div>
            <div class="payment__form">
                <form action="" method="">
                    <div class="checkbox__container">
                        <input type="radio" value="reception" name="paymethod" id="reception">
                        <label for="reception">При получении</label>
                    </div>
                    <div class="checkbox__container">
                        <input type="radio" value="online" name="paymethod" id="online">
                        <label for="online">Онлайн</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="payment__partners">
            <div class="paypartners__item">
                <img src="{% static 'img/pay_webmoney.jpg' %}" alt="">
            </div>
            <div class="paypartners__item">
                <img src="{% static 'img/pay_yandex.png' %}" alt="">
            </div>
            <div class="paypartners__item">
                <img src="{% static 'img/pay_qivi.png' %}" alt="">
            </div>
            <div class="paypartners__item">
                <img src="{% static 'img/pay_visa.png' %}" alt="">
            </div>
        </div>
    </div>

{% endblock %}

templates/shop/user_registration.html
{% extends 'generic_template.html' %}

{% block content %}
    <form class="form-row" method="post" action="{% url 'shop:user_registration' %} ">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Створити">
    </form>
{% endblock %}