maki_new/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from maki_new import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls', namespace='shop')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.GoodsList.as_view(), name='index'),
    path('reg_user', views.UserRegistration.as_view(), name='user_registration'),
    path('<int:pk>', views.GoodDetail.as_view(), name='detail'),
    path('comment', views.CommentSave.as_view(), name='comment_save'),
    path('add_to_basket/<int:pk>', views.add_to_basket, name='add_to_basket'),
    path('remove_from_basket', views.del_good_from_basket, name='remove_good'),
    path('basket', views.BasketShow.as_view(), name='basket'),
    path('order', views.Order.as_view(), name='order'),
    path('oder_id/<int:pk>', views.show_order, name="show_order"),
]

templates/generic_template.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static  'css/fonts.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/jquery-ui.structure.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/lightslider.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/main.min.css' %}">

</head>
<body>

<header class="header">
    <div class="header__top">
        <div class="wrapper">
            <div class="header__search">
                <input class="search__field" type="search" placeholder="Что вы ищите?">
                <a class="search__btn" href="#"></a>
            </div>

            <div class="toggle__menu">
                <span class="toggle__top"></span>
                <span class="toggle__mid"></span>
                <span class="toggle__bot"></span>
            </div>

            <nav class="main__menu">
                <ul>
                    <li><a href="#">Доставка</a></li>
                    <li><a href="#">Оплата</a></li>
{#                    <li><a href="#">Гарантии</a></li>#}
                    <li><a href="#">Контакты</a></li>
                    <li><a href="{% url 'shop:user_registration' %}">Зареєструватись</a></li>
                    <li>{% if not user.is_authenticated %}
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <div >
                                <label > Login</label>
                                <input type="text" name="username">

                            </div>
                            <div >
                                <label > Password</label>
                                <input type="password" name="password">

                                <input type="submit" style="margin-left: 10px" value="Login">
                        </form>
                    {% else %}
                        <a class="nav-link" href="{% url 'logout' %}">Logout - {{ user.username }}</a>
                    {% endif %}</li>
                </ul>

{#                <li>#}
                    {#            class="nav-item active"#}
{#                    {% if user.is_authenticated %}#}
{#                        <a class="nav-link" href="{% url 'logout' %}">Logout - {{ user.username }}<span class="sr-only">(current)</span></a>#}
{#                    {% else %}#}
{#                        <a class="nav-link" href="{% url 'login' %}">Sign in<span class="sr-only">(current)</span></a>#}
{#                    {% endif %}#}




{#                </li>#}

            </nav>
        </div>
    </div>
    <div class="header__mid">
        <div class="wrapper">
            <div class="col_pull clearfix">
                <div class="col_x3">
                    <div class="header__logo">
                        <a href="{% url 'shop:index' %}">
                            <img src="{% static 'img/logo.png' %}" alt="logo">
                            <span class="logo__text">Интернет-магазин цветов</span>
                        </a>
                    </div>
                </div>
                <div class="col_x3">
                    <div class="header__contact">
                        <div class="header__adress">г. <span class="text_bold">Челябинск,</span> ул. Воровского, 30A
                        </div>
                        <div class="header__email">e-mail: buket@mail.ru</div>
                        <div class="header__phone">
                            <a href="tel:83515672146"><span class="phone_pink">8(351)</span> 567 21 46</a>
                        </div>
                    </div>
                </div>
                <div class="col_x3">
                    {% if not order %}
                        <div class="header__order">
                            <a href="{% url 'shop:basket' %}" class="order__btn">Корзина</a>
                            <div class="order__text">
                                <p class=""><span class=" text_bold">{{ total_quantity }}</span> товаров</p>
                                <p class="">На сумму <span class=" text_bold">{{ sum }} руб.</span></p>
                            </div>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <div class="header__bot">
        <div class="wrapper">
            <ul class="header__tabs clearfix">
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_bouquets.png' %}" alt="bouquets">
                        </div>
                        <span class="tab__text">Букеты</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_flowers.png' %}" alt="flowers">
                        </div>
                        <span class="tab__text">Цветы</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_roses.png' %}" alt="roses">
                        </div>
                        <span class="tab__text">Розы</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_compositions.png' %}" alt="compositions">
                        </div>
                        <span class="tab__text">Композиции</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_gifts.png' %}" alt="gifts">
                        </div>
                        <span class="tab__text">Подарки</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="tab__img">
                            <img src="{% static 'img/tab_weddings.png' %}" alt="weddings">
                        </div>
                        <span class="tab__text">Свадебные букеты</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<div class="news">
    <div class="wrapper">
        <div class="news__head clearfix">
            <p class="section__title news__title">Новости</p>
            <a class="news__list" href="#">Все новости</a>
        </div>
        <div class="news__cols clearfix">
            <div class="col_x3">
                <div class="news__item">
                    <div class="news__images">
                        <img src="{% static 'img/img_news-1.jpg' %}" alt="">
                        <a href="#" class="news__hover"></a>
                    </div>
                    <div class="news__content">
                        <p class="news__date">01.01.16</p>
                        <a href="#" class="news__text">С Новым годом 2016!</a>
                    </div>
                </div>
            </div>
            <div class="col_x3">
                <div class="news__item">
                    <div class="news__images">
                        <img src="{% static 'img/img_news-2.jpg' %}" alt="">
                        <a href="#" class="news__hover"></a>
                    </div>
                    <div class="news__content">
                        <p class="news__date">01.01.16</p>
                        <a href="#" class="news__text">Как украсить дом к Новому году?</a>
                    </div>
                </div>
            </div>
            <div class="col_x3">
                <div class="news__item">
                    <div class="news__images">
                        <img src="{% static 'img/img_news-3.jpg' %}" alt="">
                        <a href="#" class="news__hover"></a></div>
                    <div class="news__content">
                        <p class="news__date">01.01.16</p>
                        <a href="#" class="news__text">Розыгрыш новогоднего подарка</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="main__footer">
    <div class="prefooter__background">
        <div class="prefooter">
            <div class="wrapper clearfix">
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">О магазине</a>
                    <a href="#" class="prefooter__item">Почему мы?</a>
                    <a href="#" class="prefooter__item">Отзывы</a>
                    <a href="#" class="prefooter__item">Скидки</a>
                </div>
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">Гарантии</a>
                    <a href="#" class="prefooter__item">Возврат денежных средств</a>
                    <a href="#" class="prefooter__item">Корпоративные букеты и подарки</a>
                </div>
                <div class="prefooter__cols col">
                    <a href="#" class="prefooter__item">Доставка</a>
                    <a href="#" class="prefooter__item">Доставка в праздничные дни</a>
                    <a href="#" class="prefooter__item">Спецпредложения к праздникам</a>
                </div>

            </div>
        </div>
    </div>
    <div class="footer__background">
        <div class="footer">
            <div class="wrapper clearfix">
                <div class="footer__contacts">
                    <a href="tel:83515672146" class="footer__phone">8 (351) <span class="text_bold">567 21 46</span></a><a
                        href="#" class="footer__mail">e-mail: buket@mail.ru</a>
                </div>
                <div class="footer__copyright">
                    <p>Служба доставки цветов &reg; 2016</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/lightslider.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

</body>
</html>